
services:
  postgres-master:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: masterpassword
      POSTGRES_USER: masteruser
      POSTGRES_DB: masterdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  master-data:
