services:
  postgres-slave:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresDB
      POSTGRES_HOST_AUTH_METHOD: trust
    command: >
      sh -c "while ! pg_isready -h 192.168.3.2 -p 5432; do sleep 1; done;
             pg_basebackup -h 192.168.3.2 -D /var/lib/postgresql/data -U slaveuser -vP -W -R -X stream -c fast"
    volumes:
      - ./slave-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  slave-data: